'use strict';
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const { once } = require('node:events');
const root = path.resolve(__dirname, '..');
const artifacts = path.join(root, 'artifacts');
fs.mkdirSync(artifacts, { recursive: true });
const dataDir = fs.mkdtempSync(path.join(artifacts, 'browser-test-'));
let server, browser, base;
const errors = [];
async function start() {
  server = spawn(process.execPath, ['--no-warnings', 'server.cjs'], { cwd: root, env: { ...process.env, PORT: '0', HOST: '127.0.0.1', DESTINY_DATA_DIR: dataDir, ADMIN_USERNAME: 'poxiao', ADMIN_PASSWORD: 'test-admin-password', ADMIN_PASSWORD_FILE: '' }, stdio: ['ignore', 'pipe', 'pipe'] });
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('Server startup timed out')), 10000);
    server.stdout.on('data', chunk => { const port = /localhost:(\d+)/.exec(String(chunk)); if (port) { base = `http://127.0.0.1:${port[1]}`; clearTimeout(timer); resolve(); } });
    server.once('error', error => { clearTimeout(timer); reject(error); });
    server.once('exit', code => { clearTimeout(timer); reject(Error(`Server exited: ${code}`)); });
    server.stderr.on('data', chunk => process.stderr.write(chunk));
  });
}
async function pageFor(options = {}) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, ...options });
  await context.addInitScript(() => {
    window.registeredTools = {};
    Object.defineProperty(document, 'modelContext', { value: { registerTool(tool) { window.registeredTools[tool.name] = tool; } } });
  });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForFunction(() => document.getElementById('auth-screen').dataset.ready === 'true');
  return page;
}
async function login(page, username, password = 'test-password') {
  await page.locator('#auth-login-tab').click();
  await page.locator('#auth-username').fill(username);
  await page.locator('#auth-password').fill(password);
  await page.locator('#auth-submit').click();
  await page.locator('#auth-screen').waitFor({ state: 'hidden' });
  assert.match(page.url(), username === 'poxiao' ? /#\/admin$/ : /#\/home$/);
}
async function register(page, username, nickname) {
  await page.locator('#auth-register-tab').click();
  await page.locator('#auth-username').fill(username);
  await page.locator('#auth-nickname').fill(nickname);
  await page.locator('#auth-password').fill('test-password');
  await page.locator('#auth-confirm').fill('test-password');
  await page.locator('#auth-submit').click();
  await page.locator('#auth-screen').waitFor({ state: 'hidden' });
  assert.match(page.url(), /#\/home$/);
  await balance(page, 0);
}
async function balance(page, value) {
  await page.waitForFunction(value => document.getElementById('balance').textContent === value.toLocaleString('zh-CN'), value);
}
async function pool(admin, id) {
  await admin.locator('[data-admin-tab="probabilities"]').click();
  for (const input of await admin.locator('[data-rate]').all()) await input.fill((await input.getAttribute('data-rate')) === id ? '100' : '0');
  await admin.locator('#guarantees-enabled').uncheck();
  await admin.locator('#probability-save').click();
  await admin.waitForFunction(() => document.getElementById('probability-message').textContent.startsWith('已保存'));
  await admin.waitForFunction(() => !document.getElementById('probability-save').disabled);
}
async function draw(page, button, count) {
  await page.locator(button).click();
  await page.locator('#modal[open]').waitFor();
  assert.equal(await page.locator('#modal .reward-card').count(), count);
}
async function screenshot(page, name) {
  if (await page.locator('#auth-screen').isVisible()) await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('.entry-content')).opacity) >= .99);
  await page.screenshot({ path: path.join(artifacts, name + '.png'), fullPage: true });
}
async function noOverflow(page, selector = 'html') {
  assert.equal(await page.locator(selector).evaluate(el => el.scrollWidth <= el.clientWidth + 2), true, `${selector} horizontal overflow`);
}
(async () => {
  await start();
  browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || undefined });
  const alice = await pageFor();
  assert.equal(await alice.locator('.app-shell').isVisible(), false);
  assert.equal(await alice.locator('#auth-message').innerText(), '');
  await screenshot(alice, 'auth-desktop');
  await alice.locator('#auth-username').fill('poxiao');
  await alice.locator('#auth-password').fill('wrong-password');
  await alice.locator('#auth-submit').click();
  await alice.waitForFunction(() => document.getElementById('auth-message').textContent.includes('不正确'));
  assert.equal(await alice.locator('.app-shell').isVisible(), false);
  assert.equal(await alice.locator('#auth-screen').evaluate(el => el.classList.contains('is-entering')), false);
  await register(alice, 'alice', '第一位宿主');
  await alice.locator('#draw-one').click();
  assert.match(await alice.locator('#toast').innerText(), /不足/);
  const bob = await pageFor({ viewport: { width: 390, height: 844 }, isMobile: true });
  await screenshot(bob, 'auth-mobile');
  await bob.locator('#auth-register-tab').click();
  await screenshot(bob, 'register-mobile');
  await bob.setViewportSize({ width: 320, height: 568 });
  await noOverflow(bob, '#auth-screen');
  await bob.locator('#auth-username').scrollIntoViewIfNeeded();
  assert.ok((await bob.locator('#auth-username').boundingBox()).y >= 0);
  await bob.locator('#auth-submit').scrollIntoViewIfNeeded();
  const submitBounds = await bob.locator('#auth-submit').boundingBox();
  assert.ok(submitBounds.y >= 0 && submitBounds.y + submitBounds.height <= 568);
  await bob.setViewportSize({ width: 390, height: 844 });
  await bob.locator('#auth-username').fill('bob');
  await bob.locator('#auth-nickname').fill('第二位宿主');
  await bob.locator('#auth-password').fill('test-password');
  await bob.locator('#auth-confirm').fill('mismatched-password');
  await bob.locator('#auth-submit').click();
  assert.match(await bob.locator('#auth-message').innerText(), /不一致/);
  await register(bob, 'bob', '第二位宿主');
  const admin = await pageFor();
  await login(admin, 'poxiao', 'test-admin-password');
  await admin.waitForFunction(() => document.getElementById('player-count').textContent === '2');
  for (const username of ['alice', 'bob']) {
    await admin.locator('.player-card').filter({ hasText: '@' + username }).locator('[data-grant-player]').click();
    await admin.locator('#grant-amount').fill('100');
    await admin.locator('#grant-submit').click();
    await admin.waitForFunction(() => document.getElementById('grant-message').textContent.startsWith('已向') && !document.getElementById('grant-submit').disabled);
  }
  await alice.bringToFront(); await balance(alice, 100);
  await bob.bringToFront(); await balance(bob, 100);
  await screenshot(admin, 'admin-desktop');
  await pool(admin, 'empty');
  await screenshot(admin, 'probabilities-desktop');
  await alice.locator('#skip-animation').check();
  await draw(alice, '#draw-ten', 10);
  await balance(alice, 0);
  await screenshot(alice, 'ten-pull');
  await alice.locator('#accept-rewards').click();
  await alice.locator('#draw-one').click();
  assert.match(await alice.locator('#toast').innerText(), /不足/);
  await alice.reload();
  await balance(alice, 0);
  await alice.waitForFunction(() => document.getElementById('total').textContent === '10');
  await alice.locator('[data-view="inventory"]').click();
  assert.equal(await alice.locator('#inventory-grid .reward-card').count(), 1);
  await alice.locator('[data-view="history"]').click();
  assert.equal(await alice.locator('.history-row').count(), 10);
  await balance(bob, 100);
  assert.equal(await bob.locator('#total').innerText(), '0');
  await admin.locator('[data-admin-tab="players"]').click();
  await admin.locator('#player-search').fill('alice');
  assert.equal(await admin.locator('.player-card').count(), 1);
  await admin.locator('.player-card [data-grant-player]').click();
  await admin.locator('#grant-amount').fill('100');
  await admin.locator('#grant-note').fill('完成任务奖励');
  await admin.locator('#grant-submit').click();
  await admin.waitForFunction(() => document.getElementById('grant-message').textContent.startsWith('已向'));
  await alice.bringToFront();
  await balance(alice, 100);
  await balance(bob, 100);
  await alice.locator('[data-view="summon"]').click();
  await alice.locator('#skip-animation').check();
  const result = await alice.evaluate(() => window.registeredTools.complete_destiny_summon.execute({ count: 1 }));
  assert.equal(result.rewards.length, 1); assert.equal(result.balance, 90);
  assert.equal((await alice.evaluate(() => window.registeredTools.read_destiny_status.execute({}))).total, 11);
  assert.equal(await alice.evaluate(async () => { try { await window.registeredTools.complete_destiny_summon.execute({ count: 2 }); return false; } catch { return true; } }), true);
  await alice.locator('#accept-rewards').click();
  await pool(admin, 'flowers');
  await draw(alice, '#draw-one', 1);
  await balance(alice, 100);
  assert.match(await alice.locator('#modal-content').innerText(), /大红花 \+20/);
  await alice.locator('#accept-rewards').click();
  await pool(admin, 'retry');
  await draw(alice, '#draw-one', 1);
  await balance(alice, 90);
  await alice.locator('#accept-rewards').click();
  await pool(admin, 'empty');
  await draw(alice, '#draw-free', 1);
  await balance(alice, 90);
  await alice.locator('#accept-rewards').click();
  assert.equal(await alice.locator('#draw-free').isVisible(), false);
  await alice.locator('#rules-button').click();
  assert.match(await alice.locator('#modal-content').innerText(), /保底已关闭/);
  await alice.keyboard.press('Escape');
  await alice.locator('#pool-button').click();
  assert.equal(await alice.locator('#modal .reward-card').count(), 9);
  await alice.locator('#modal .reward-image').evaluateAll(images => Promise.all(images.map(image => image.decode())));
  await alice.keyboard.press('Escape');
  await alice.locator('#account-button').click();
  await alice.locator('#logout-button').click();
  await alice.locator('#auth-screen').waitFor({ state: 'visible' });
  await login(alice, 'bob');
  await balance(alice, 100);
  assert.equal(await alice.locator('#history-list .history-row').count(), 0);
  await alice.locator('#account-button').click();
  await alice.locator('#logout-button').click();
  await login(alice, 'alice');
  await balance(alice, 90);
  assert.equal(await alice.locator('#total').innerText(), '14');
  await screenshot(alice, 'desktop');
  await noOverflow(bob); await screenshot(bob, 'mobile');
  await bob.locator('#skip-animation').uncheck();
  await bob.locator('#draw-one').click();
  await bob.locator('#summon-cinematic[open]').waitFor();
  await screenshot(bob, 'mobile-cinematic');
  await bob.locator('#skip-cinematic').click();
  await bob.locator('#modal[open]').waitFor();
  await balance(bob, 90); await noOverflow(bob, '#modal');
  await bob.locator('#accept-rewards').click();
  await bob.locator('#draw-one').click();
  await bob.locator('#summon-cinematic[data-phase="reveal"]').waitFor();
  await screenshot(bob, 'cinematic-reveal');
  await bob.locator('#modal[open]').waitFor();
  await balance(bob, 80);
  await bob.locator('#accept-rewards').click();
  const mobileAdmin = await pageFor({ viewport: { width: 390, height: 844 }, isMobile: true });
  await login(mobileAdmin, 'poxiao', 'test-admin-password');
  await mobileAdmin.waitForFunction(() => document.getElementById('player-count').textContent === '2');
  await noOverflow(mobileAdmin, '#admin-dialog'); await screenshot(mobileAdmin, 'admin-mobile');
  await mobileAdmin.locator('[data-admin-tab="probabilities"]').click();
  await noOverflow(mobileAdmin, '#admin-probabilities-panel');
  await mobileAdmin.locator('#probability-save').scrollIntoViewIfNeeded();
  await screenshot(mobileAdmin, 'probabilities-mobile');
  await mobileAdmin.locator('[data-admin-tab="logs"]').click();
  assert.ok(await mobileAdmin.locator('.audit-row').count() >= 5);
  await screenshot(mobileAdmin, 'logs-mobile');
  const reduced = await pageFor({ viewport: { width: 390, height: 650 }, reducedMotion: 'reduce' });
  assert.equal(await reduced.locator('.entry-orbit').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await login(reduced, 'alice');
  await balance(reduced, 90);
  await admin.locator('[data-admin-tab="prayers"]').click();
  await admin.waitForFunction(() => document.querySelectorAll('.admin-prayer-row').length === 16);
  assert.match(await admin.locator('#prayer-summary').innerText(), /共 16 条/);
  await screenshot(admin, 'admin-prayers-desktop');
  await admin.locator('#prayer-player').selectOption({ label: '第二位宿主 (@bob)' });
  await admin.waitForFunction(() => document.querySelectorAll('.admin-prayer-row').length === 2);
  assert.ok((await admin.locator('#admin-prayers').innerText()).includes('@bob'));
  assert.ok(!(await admin.locator('#admin-prayers').innerText()).includes('@alice'));
  await admin.locator('[data-admin-tab="players"]').click();
  await admin.locator('#player-search').fill('alice');
  await admin.locator('[data-prayer-player]').click();
  await admin.waitForFunction(() => document.querySelectorAll('.admin-prayer-row').length === 14);
  await mobileAdmin.locator('[data-admin-tab="prayers"]').click();
  await mobileAdmin.waitForFunction(() => document.querySelectorAll('.admin-prayer-row').length === 16);
  await noOverflow(mobileAdmin, '#admin-prayers-panel');
  await screenshot(mobileAdmin, 'admin-prayers-mobile');
  const newcomer = await pageFor();
  await newcomer.locator('#auth-register-tab').click();
  await mobileAdmin.locator('[data-admin-tab="settings"]').click();
  await mobileAdmin.locator('#registration-enabled').uncheck();
  await mobileAdmin.locator('#system-settings-save').click();
  await mobileAdmin.waitForFunction(() => document.getElementById('settings-message').textContent.includes('已保存') && !document.getElementById('system-settings-save').disabled);
  await screenshot(mobileAdmin, 'admin-settings-mobile');
  await noOverflow(mobileAdmin, '#admin-settings-panel');
  await newcomer.bringToFront();
  await newcomer.waitForFunction(() => document.getElementById('auth-register-tab').disabled);
  assert.equal(await newcomer.locator('#registration-notice').isVisible(), true);
  assert.equal(await newcomer.locator('#auth-nickname-row').isVisible(), false);
  const blocked = await newcomer.request.post(base + '/api/register', { data: { username: 'blocked_ui', password: 'test-password' } });
  assert.equal(blocked.status(), 403);
  await screenshot(newcomer, 'registration-closed');
  await login(newcomer, 'bob'); await balance(newcomer, 80);
  await admin.locator('[data-admin-tab="settings"]').click();
  await admin.locator('#system-settings-save').click();
  await admin.waitForFunction(() => document.getElementById('settings-message').textContent.includes('其他页面'));
  await admin.locator('#admin-refresh').click();
  await admin.waitForFunction(() => !document.getElementById('registration-enabled').checked);
  await screenshot(admin, 'admin-settings-desktop');
  await admin.locator('#registration-enabled').check();
  await admin.locator('#system-settings-save').click();
  await admin.waitForFunction(() => document.getElementById('settings-message').textContent.includes('已保存') && !document.getElementById('system-settings-save').disabled);
  const reopened = await pageFor();
  await reopened.waitForFunction(() => !document.getElementById('auth-register-tab').disabled);
  await register(reopened, 'newcomer', '新来的宿主');
  await admin.locator('#admin-refresh').click();
  await admin.waitForFunction(() => document.getElementById('player-count').textContent === '3');
  await admin.locator('[data-admin-tab="prayers"]').click();
  await admin.locator('#prayer-player').selectOption({ label: '新来的宿主 (@newcomer)' });
  await admin.waitForFunction(() => document.getElementById('prayer-summary').textContent.includes('共 0 条'));
  assert.equal(await admin.locator('.admin-prayer-row').count(), 0);
  await admin.locator('[data-admin-tab="logs"]').click();
  assert.match(await admin.locator('#admin-logs').innerText(), /新宿主注册已开放/);
  assert.match(await admin.locator('#admin-logs').innerText(), /新宿主注册已关闭/);
  assert.deepEqual(errors, []);
  console.log('PASS: desktop/mobile registration, login/logout, admin player list/search/grants, live balance sync, probabilities, account isolation, server draws, free/flower rewards, reload persistence, inventory/history, animations, image loading, responsive admin panels, WebMCP adapter');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (browser) await browser.close();
  if (server && server.exitCode === null) { const exited = once(server, 'exit'); server.kill(); await exited; }
});
