const assert = require('node:assert/strict');
const { fresh, draw, validate, ITEMS } = require('../dist/engine.js');
assert.equal(fresh().balance, 0, 'new hosts start without flowers');
assert.throws(() => draw(fresh(), 1), /大红花不足/);
const funded = () => ({ ...fresh(), balance: 100 });
let s = funded();
const ten = draw(s, 10, () => .5, 1000);
assert.equal(s.balance, 100, 'draw must not mutate original state');
assert.equal(ten.state.balance, 0);
assert.equal(ten.results.filter(i => i.rarity === 'SR').length, 1);
assert.equal(ten.results[9].rarity, 'SR');
assert.equal(ten.state.total, 10);
assert.ok(validate(ten.state));
assert.throws(() => draw(ten.state, 1), /不足/);
assert.throws(() => draw(s, 2), /仅支持/);
s.balance = 10 * 80;
for (let i = 0; i < 79; i++) s = draw(s, 1, () => .5).state;
assert.equal(s.pitySSR, 79);
const guarantee = draw(s, 1, () => .5);
assert.equal(guarantee.results[0].rarity, 'SSR');
assert.equal(guarantee.state.pitySSR, 0);
assert.equal(guarantee.state.pitySR, 0);
const early = draw({ ...funded(), pitySSR: 50, pitySR: 5 }, 1, () => 0);
assert.equal(early.results[0].rarity, 'SSR');
assert.equal(early.state.pitySSR, 0);
assert.equal(early.state.pitySR, 0);
let singles = { ...fresh(), balance: 1000 }, batches = { ...fresh(), balance: 1000 };
for (let i = 0; i < 100; i++) singles = draw(singles, 1, () => .5, 1000).state;
for (let i = 0; i < 10; i++) batches = draw(batches, 10, () => .5, 1000).state;
assert.deepEqual(singles, batches, 'single and ten pulls share guarantees');
s = { ...fresh(), balance: 10 * 250 };
for (let i = 0; i < 25; i++) s = draw(s, 10, () => .5, 1000).state;
assert.equal(s.history.length, 200);
assert.equal(s.total, 250);
assert.equal(Object.values(s.inventory).reduce((a, b) => a + b), 250);
assert.ok(validate(s));
assert.equal(validate({ ...s, pitySR: 10 }), null);
assert.equal(validate({ ...s, inventory: { unknown: 1 } }), null);
assert.equal(validate({ ...s, balance: -1 }), null);
assert.equal(draw(funded(), 1, () => .5).state.balance, 90, 'single draw consumes ten flowers');
assert.throws(() => draw({ ...fresh(), balance: 9 }, 1), /大红花不足/);
assert.equal(draw({ ...fresh(), balance: 10 }, 1, () => .5).state.balance, 0);
const migrated = validate({ ...s, version: 1, balance: 1440 });
assert.equal(migrated.version, 3);
assert.equal(migrated.balance, 90);
assert.deepEqual(migrated.inventory, s.inventory);
assert.equal(migrated.total, s.total);
assert.equal(validate(migrated).balance, 90, 'migration must not run twice');
assert.equal(ITEMS.length, 9);
assert.equal(ITEMS.filter(i => i.rarity === 'SSR').length, 1);
assert.equal(ITEMS.filter(i => i.rarity === 'SR').length, 3);
assert.equal(ITEMS.filter(i => i.rarity === 'R').length, 5);
assert.equal(new Set(ITEMS.filter(i => i.rarity === 'SR').map(i => i.image)).size, 1);
function rolls(...values) { let n = 0; return () => values[n++ % values.length]; }
const flower = draw(funded(), 1, rolls(.5, .9));
assert.equal(flower.results[0].id, 'flowers');
assert.equal(flower.state.balance, 110, 'deduct 10 and immediately credit 20');
assert.equal(validate(flower.state).balance, 110, 'loading does not grant reward again');
const retry = draw({ ...fresh(), balance: 10 }, 1, rolls(.5, .01));
assert.equal(retry.results[0].id, 'retry');
assert.equal(retry.state.balance, 0);
assert.equal(retry.state.freeDraws, 1);
const free = draw(retry.state, 1, rolls(.5, .3), 2000, true);
assert.equal(free.state.balance, 0);
assert.equal(free.state.freeDraws, 0);
assert.equal(free.state.total, 2);
assert.equal(free.state.pitySSR, 2);
assert.equal(free.results[0].id, 'empty');
assert.throws(() => draw(free.state, 1, rolls(.5, .3), 2000, true), /没有可用/);
assert.throws(() => draw(retry.state, 10, rolls(.5, .3), 2000, true), /没有可用/);
const freeRepeat = draw(retry.state, 1, rolls(.5, .01), 2000, true);
assert.equal(freeRepeat.state.freeDraws, 1, 'new retry credit replaces the consumed credit');
const multiFlower = draw(funded(), 10, rolls(.5, .9));
assert.equal(multiFlower.state.balance, 180, 'nine flower rewards and one epic guarantee');
const legacy = validate({ version: 2, balance: 90, total: 1, pitySSR: 1, pitySR: 1, inventory: { sword: 1 }, history: [{ id: 'sword', time: 1000, number: 1 }], gifts: 0 });
assert.equal(legacy.version, 3);
assert.equal(legacy.freeDraws, 0);
assert.equal(legacy.inventory.sword, 1);
assert.equal(legacy.balance, 90);
assert.ok(validate(draw(legacy, 1, rolls(.5, .3)).state));
console.log('PASS: balance, ten-pull guarantee, 80-pull guarantee, reset, single/batch parity, history cap, save validation');
const limitedBatch = draw({ ...fresh(), balance: 100 }, 10, () => 0);
assert.equal(limitedBatch.results.filter(item => item.id === 'shinchan').length, 1, 'ten draws can only grant one limited item');
const owned = { ...limitedBatch.state, balance: 2000, freeDraws: 1, pitySSR: 79, pitySR: 9 };
assert.equal(draw(owned, 1, () => .99).results[0].rarity, 'SR', 'legendary limit does not disable epic guarantee');
assert.notEqual(draw(owned, 1, () => 0, 0, true).results[0].id, 'shinchan', 'free draws respect per-player limit');
let limited = owned;
for (let i = 0; i < 10; i++) limited = draw(limited, 10, () => 0).state;
assert.equal(limited.inventory.shinchan, 1);
assert.equal(draw({ ...owned, inventory: { ...owned.inventory, shinchan: 3 } }, 1, () => 0).state.inventory.shinchan, 3, 'legacy copies retained but no new copies');
const { availableRates } = require('../dist/engine.js');
assert.equal(availableRates(owned).shinchan, 0);
assert.ok(Math.abs(availableRates(owned).empty - 17 / 98 * 100) < 1e-9);
const allLimited = { rates: Object.fromEntries(ITEMS.map(i => [i.id, i.id === 'shinchan' ? 100 : 0])), guarantees: false };
const untouched = { ...fresh(), balance: 100 };
assert.throws(() => draw(untouched, 10, () => 0, 0, false, allLimited), /可抽奖励已领完/);
assert.deepEqual(untouched, { ...fresh(), balance: 100 }, 'failed batch must not charge or partially grant');
console.log('PASS: per-player limit, ten/free draws, legacy inventory, epic guarantee, normalized rates, empty pool atomicity');
